Vagrant.configure("2") do |config|
  config.vm.network "public_network", use_dhcp_assigned_default_route: true, :bridge => "eno1"
  config.vm.define :master do |node|
    node.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "master", "--memory", "2048"]
    end
    node.vm.box = "ubuntu-xenial-docker"
    node.vm.hostname = "master"
  end

  config.vm.define :node01 do |node|
    node.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "node01", "--memory", "2048"]
    end
    node.vm.box = "ubuntu-xenial-docker"
    node.vm.hostname = "node01"
  end

  config.vm.define :node02 do |node|
    node.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "node02", "--memory", "2048"]
    end
    node.vm.box = "ubuntu-xenial-docker"
    node.vm.hostname = "node02"
  end
end