Vagrant.configure("2") do |config|
  config.vm.network "public_network", use_dhcp_assigned_default_route: true, :bridge => "wlp4s0"
  config.vm.define :master do |node|
    node.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "master", "--memory", "1200"]
    end
    node.vm.box = "ubuntu-xenial-docker"
    node.vm.hostname = "master"
    node.vm.synced_folder "/home/mu-mo/公共的", "/home/vagrant/share"
  end

  config.vm.define :node01 do |node|
    node.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "node01", "--memory", "1200"]
    end
    node.vm.box = "ubuntu-xenial-docker"
    node.vm.hostname = "node01"
    node.vm.synced_folder "/home/mu-mo/公共的", "/home/vagrant/share"
  end
end